/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package distributed.systems.gridscheduler.neogui;

import java.awt.*;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Glenn
 */
public class RGSStatusFrame extends javax.swing.JFrame {

    private RGSStatusFrameData data;
    private final List<RRMStatusPanel> registeredPanels;

    public RGSStatusFrame(RGSStatusFrameData data) {
        this.data = data;
        initComponents();
        registeredPanels = new ArrayList<>();
    }

    public void addPanel(RRMStatusPanel panel) {
        registeredPanels.add(panel);
        innerPanel.add(panel);
        Dimension nextDimension = innerPanel.getPreferredSize();
        nextDimension.height += panel.getPreferredSize().height;
        innerPanel.setPreferredSize(nextDimension);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JLabel();
        nameValue = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        scrollPane = new javax.swing.JScrollPane();
        innerPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(230, 2147483647));
        setMinimumSize(new java.awt.Dimension(230, 600));
        setPreferredSize(new java.awt.Dimension(230, 600));

        header.setText("Grid Scheduler");

        nameValue.setText(data.getNameValue());

        innerPanel.setPreferredSize(new java.awt.Dimension(0, 0));
        innerPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));
        scrollPane.setViewportView(innerPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPane)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(header)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                        .addComponent(nameValue)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(header)
                    .addComponent(nameValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel header;
    private javax.swing.JPanel innerPanel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel nameValue;
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables
}
